### ISSUE TITLE
Equivalent class

### ISSUE THREAD

**Issue by RichDijk** [cknoll/yamlpyowl#4]
Hi, 

Thank for the nice work so far. I might have a use case for modelling rather small ontologies using this tool.

So I am trying the following:
 
```
- owl_class:
    Class1:
        SubClassOf: "owl:Thing"

- owl_data_property:
    functieCode:
        Domain: Class1
        Range: int 

- owl_class:
    Overeenkomst:
        SubClassOf: (functieCode value 100) or (functieCode value 110)
```
But running Python 3.9.8 I get 

> UnknownEntityError: unknown entity name: (functieCode value 100) or (functieCode value 110) while processing dict: {'SubClassOf': '(functieCode value 100) or (functieCode value 110)'}
> 
> This error occurred while parsing the `inner_dict`: {'Overeenkomst': {'SubClassOf': '(functieCode value 100) or (functieCode value 110)'}}.

Is this unsupported or are the syntax and semantics different?

Regards, Richard

**Comment by cknoll** [comment]
Unfortunately, this is currently not supported.
yamlpyowl (currently) supports only a (small) subset of owl constructs.

Suggestion:

If you could provide owlready2-based python code representing your example, I could have a look on how to add yaml support for such constructs.

Its possible that it is easy to implement, but I am not sure yet.

**Comment by RichDijk** [comment]
Thank you. 

I will create some Python code a feed back that to you.

**Comment by RichDijk** [comment]
So far I have created RDF using infixowl based on a pydal model.
This must be more generalized, pydal replaced by yaml and infixowl replaced by owlready2
```
from rdflib import Graph, Namespace, URIRef, Literal, BNode
from rdflib.namespace import OWL

def get_ns_uri(graph, prefix):
    uri = None
    for t in graph.namespaces():
        if t[0] == prefix:
            uri = URIRef(t[1])
    return uri 

def create_local_onto_rdflib():
    from gluon import current
    db = current.db
    from rdflib.extras.infixowl import Class, Property, Restriction
    from rdflib.namespace import NamespaceManager
 
    ns_dict= {}
    LO = Namespace('http://www.ex.org/data#')
    VPHPERS = Namespace('http://purl.org/ozo/vph-pers#')
    ns_dict['lo'] = LO
    ns_dict['vph-pers'] = VPHPERS
    ns_dict['owl'] = OWL
    g = Graph()
    for ns in ns_dict:
        g.bind(ns, ns_dict[ns])

    sc_list = db(db.lo_subclassof.id>0).select()
    prop_list = db(db.lo_property.id>0).select()
    eqclss_list = db(db.lo_eqclass_oflijst.id>0).select()

    for sc in sc_list:
        # The class is always in the local ontology namespace
        new_class = Class(LO[sc.clss], graph=g)
        if sc.label:
            new_class.label = Literal(sc.label)
        if sc.subclassof_new:
            # Superclass maybe in an other namespace
            if ":" in sc.subclassof_new:
                ns_uri = get_ns_uri(g, sc.subclassof_new.split(":")[0])
                ns = ns_uri[sc.subclassof_new.split(":")[0]]
                lname = sc.subclassof_new.split(":")[1]
                qname = ns[lname]
            else:
                lname = sc.subclassof_new
                qname = LO[lname]
            new_class.subClassOf = [qname]
        if sc.subclassof_vph:
            new_class.subClassOf = [URIRef(sc.subclassof_vph)]

    for prop in prop_list:
        new_prop = Property(LO[prop.property], graph=g)
        if prop.label:
            new_prop.label = Literal(prop.label)
        if prop.domain_lo:
            new_prop.domain = [URIRef(prop.domain_lo)]
        if prop.domain_vph:
            new_prop.domain = [URIRef(prop.domain_vph)]

    for eq in eqclss_list:
        # Create equivalent class met properties restrictions
        if ":" in eq.clss_new:
            # vph of other voc class
            new_eq_class = Class(URIRef(eq.clss_new), graph=g)
        else:
            # local ontology class
            new_eq_class = Class(LO[eq.clss_new], graph=g)

        prop_restriction = None
        if eq.of_lijst: # list of ; seperated values
            if ';' in eq.of_lijst:
                # handle first value restriction
                prop_restriction = Restriction(LO[eq.property], 
                    graph=g, value=Literal(eq.of_lijst.split(";")[0]))
                # Add flowing restructions
                for value in eq.of_lijst.split(";")[1:]:
                    prop_restriction = prop_restriction | Restriction(LO[eq.property], graph=g, value=Literal(value))
            else:
                prop_restriction = Restriction(LO[eq.property], graph=g, value=Literal(eq.of_lijst))

        if eq.res_clss:
            # restriction class is always part of local model
            _res_clss = db.lo_subclassof[eq.res_clss]
            res_clss = Class(LO[_res_clss.clss], graph=g)
        
        if res_clss:
            new_eq_class.equivalentClass = [ res_clss & prop_restriction ]
        else:
            new_eq_class.equivalentClass = [ prop_restriction ]

    g_str = g.serialize()
    return dict(g_str=g_str)
```

**Comment by cknoll** [comment]
That is quite some of code with a lot of details which I currently do not understand (cause I did not try). What I meant was more or less an minimal implementation of your YAML-example. So I created one my self, see https://nbviewer.org/github/cknoll/demo-material/blob/main/expertise_system/value_restriction.ipynb. 

Note I used `equivalent_to` instead of `is_a` ( ≙`SubClassOf`) because I wanted to check whether the reasoner can actually infer the class of some instances (simple form of unit test so to say).


Does this notebook capture the semantics you need?

**Comment by RichDijk** [comment]
Sorry for the details but this is what I needed going from limited ontology editor to OWL. 
You have made a nice lean example and yes, that are the semantics I (and others because equivalent classes are common practices) need.

**Comment by cknoll** [comment]
I am working on implementing the syntax for your use case. It might however get more complicated than initially thought. This is the first parser I am implementing and thus I learn as I go.

**Comment by cknoll** [comment]
I put some time on this issue and now at least your initial example works (with slightly adapted syntax though).

See the updated demo-notebook: https://nbviewer.org/github/cknoll/demo-material/blob/main/expertise_system/value_restriction.ipynb

This is the content of the yaml file:

```yaml
- iri: http://yet.undefined.org/yamlpyowl/issue4-demo.owl
- annotation: >

    Mininal example to demonstrate some features of yamlpyowl Python package.
    See https://github.com/cknoll/yamlpyowl/issues/4 for background information

- owl_class:
    Class1:
        SubClassOf: "owl:Thing"

- owl_data_property:
    functieCode:
        Domain: Class1
        Range: int

- owl_class:
    Overeenkomst1:
        # note: this makes this class a subclass of Class1 due to the domain of the property
        SubClassOf:
            Or:
                - functieCode:
                    value: 100
                - functieCode:
                    value: 200
- owl_class:
    Overeenkomst2:
        # note: this makes this class a subclass of Class1 due to the domain of the property
        EquivalentTo:
            Or:
                - functieCode:
                    value: 100
                - functieCode:
                    value: 110

- owl_individual:
      instance1:
        types:
          - Class1

- property_facts:
    functieCode:
        Facts:
            - instance1:
                - 100
                - 110

```


I made the example slightly 'less minimal' to show that the reasoner deduces the expected output for the one instance (aka individual) and to show the difference between `SubclassOf` and `EquivalentTo`. I hope this helps.


Note: the current development version of yamlpyowl (0.3.0) is not yet released in pypi.
